### PR TITLE
Signpost Linux-specific pages, add equivalent CheriBSD link and rename feature matrix page

### PR DESCRIPTION
**Pull request by jrtc27**
As discussed earlier today. See the commit messages for more details.

image

### CODE REVIEW

**Comment by jrtc27** [comment]
Cc @fvincenzo @nicholsonmarkjames (seems I'm not able to request reviewers?)

**Comment by jrtc27** [comment]
There's still the issue that the two guide links here are to the linux.morello-project.org site:

image

I don't immediately have a good idea for how to not bias those towards Linux, though until that's done they should at least say Linux somewhere.

**Review by brooksdavis — APPROVED** [review]
LGTM.

There's a longer term question about how to present other OS-ish ports like seL4 or CheriFreeRTOS when they come along since the matrix won't make a lot of sense, but that's something to ponder not something to solve today.

**Review by kwitaszczyk — APPROVED** [review]

**Comment by fvincenzo** [comment]
Hi Jessica,

Thank you for your patch.

Unfortunately it does not fit our current design for the website. As explained during the meeting yesterday we are preparing **https://docs.morello-project.org** as the new home for all the documentation about Morello, and we would be delighted to host CheriBSD documentation there. Once we are close to release it we can discuss on how to integrate your changes there.

Thanks and Regards,
Vincenzo

**Pull request closed without merging**
